EXCHANGES:
  - EXCHANGE: AEB
    ENABLED: true
    BUY_PREPARE_TIME: "09:40"
    SIGNAL_TIME: "09:46"
    EOD_RECONCILE_TIME: "18:40"
    FORCED_SELL_MODE: FIXED
    FORCED_SELL_TIME: "17:00"
    MAX_OPEN_POSITIONS: 1
    MAX_HOLDING_DAY: 7
    STOP_LOSS_PCT: 3
    BUDGET_PCT: 0.30
    CURRENCY: EUR

  - EXCHANGE: NASDAQ
    ENABLED: true
    BUY_PREPARE_TIME: "15:40"
    SIGNAL_TIME: "15:47"
    EOD_RECONCILE_TIME: "23:55"
    FORCED_SELL_MODE: FIXED
    FORCED_SELL_TIME: "20:30"
    MAX_OPEN_POSITIONS: 2
    MAX_HOLDING_DAY: 7
    STOP_LOSS_PCT: 2
    BUDGET_PCT: 0.40
    CURRENCY: USD

  - EXCHANGE: NYSE
    ENABLED: true
    BUY_PREPARE_TIME: "15:40"
    SIGNAL_TIME: "15:47"
    EOD_RECONCILE_TIME: "23:55"
    FORCED_SELL_MODE: FIXED
    FORCED_SELL_TIME: "20:30"
    MAX_OPEN_POSITIONS: 2
    MAX_HOLDING_DAY: 7
    STOP_LOSS_PCT: 2
    BUDGET_PCT: 0.30
    CURRENCY: USD